// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelterApi.Models;

#nullable disable

namespace ShelterApi.Migrations
{
    [DbContext(typeof(ShelterApiContext))]
    [Migration("20240910205546_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Adoptable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Attitude")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Adoptable = true,
                            Age = 3,
                            Attitude = "Friendly",
                            Name = "Bella",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Adoptable = true,
                            Age = 5,
                            Attitude = "Curious",
                            Name = "Max",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Adoptable = false,
                            Age = 2,
                            Attitude = "Calm",
                            Name = "Milo",
                            Species = "Rabbit"
                        },
                        new
                        {
                            AnimalId = 4,
                            Adoptable = true,
                            Age = 7,
                            Attitude = "Playful",
                            Name = "Luna",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Adoptable = false,
                            Age = 4,
                            Attitude = "Independent",
                            Name = "Oscar",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            Adoptable = true,
                            Age = 1,
                            Attitude = "Timid",
                            Name = "Daisy",
                            Species = "Guinea Pig"
                        },
                        new
                        {
                            AnimalId = 7,
                            Adoptable = true,
                            Age = 6,
                            Attitude = "Protective",
                            Name = "Charlie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Adoptable = false,
                            Age = 9,
                            Attitude = "Affectionate",
                            Name = "Whiskers",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Adoptable = true,
                            Age = 8,
                            Attitude = "Loyal",
                            Name = "Buddy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Adoptable = true,
                            Age = 1,
                            Attitude = "Energetic",
                            Name = "Nibbles",
                            Species = "Hamster"
                        },
                        new
                        {
                            AnimalId = 11,
                            Adoptable = true,
                            Age = 2,
                            Attitude = "Excitable",
                            Name = "Rocky",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 12,
                            Adoptable = true,
                            Age = 3,
                            Attitude = "Shy",
                            Name = "Lily",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 13,
                            Adoptable = true,
                            Age = 4,
                            Attitude = "Stubborn",
                            Name = "Buster",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 14,
                            Adoptable = true,
                            Age = 6,
                            Attitude = "Playful",
                            Name = "Mittens",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 15,
                            Adoptable = true,
                            Age = 2,
                            Attitude = "Gentle",
                            Name = "Fuzzy",
                            Species = "Rabbit"
                        },
                        new
                        {
                            AnimalId = 16,
                            Adoptable = false,
                            Age = 10,
                            Attitude = "Calm",
                            Name = "Smokey",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 17,
                            Adoptable = true,
                            Age = 7,
                            Attitude = "Reserved",
                            Name = "Shadow",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 18,
                            Adoptable = true,
                            Age = 1,
                            Attitude = "Talkative",
                            Name = "Ziggy",
                            Species = "Parrot"
                        },
                        new
                        {
                            AnimalId = 19,
                            Adoptable = false,
                            Age = 5,
                            Attitude = "Lazy",
                            Name = "Patches",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 20,
                            Adoptable = true,
                            Age = 6,
                            Attitude = "Protective",
                            Name = "Pepper",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 21,
                            Adoptable = true,
                            Age = 3,
                            Attitude = "Curious",
                            Name = "Coco",
                            Species = "Hamster"
                        },
                        new
                        {
                            AnimalId = 22,
                            Adoptable = false,
                            Age = 9,
                            Attitude = "Independent",
                            Name = "Tiger",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 23,
                            Adoptable = true,
                            Age = 4,
                            Attitude = "Energetic",
                            Name = "Rex",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 24,
                            Adoptable = true,
                            Age = 2,
                            Attitude = "Nervous",
                            Name = "Chloe",
                            Species = "Guinea Pig"
                        },
                        new
                        {
                            AnimalId = 25,
                            Adoptable = true,
                            Age = 5,
                            Attitude = "Friendly",
                            Name = "Ginger",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
